bnc_classcode = {'S brdcast discussn': ['Spoken', 'talk'],
 'S brdcast documentary': ['Spoken', 'talk'],
 'S brdcast news': ['Spoken', 'talk'],
 'S classroom': ['Spoken', 'talk'],
 'S consult': ['Spoken', 'talk'],
 'S conv': ['Spoken', 'talk'],
 'S courtroom': ['Spoken', 'talk'],
 'S demonstratn': ['Spoken', 'talk'],
 'S interview': ['Spoken', 'talk'],
 'S interview oral history': ['Spoken', 'talk'],
 'S lect commerce': ['Spoken', 'lectures'],
 'S lect humanities arts': ['Spoken', 'lectures'],
 'S lect nat science': ['Spoken', 'lectures'],
 'S lect polit law edu': ['Spoken', 'lectures'],
 'S lect soc science': ['Spoken', 'lectures'],
 'S meeting': ['Spoken', 'talk'],
 'S parliament': ['Spoken', 'talk'],
 'S pub debate': ['Spoken', 'talk'],
 'S sermon': ['Spoken', 'lectures'],
 'S speech scripted': ['Spoken', 'lectures'],
 'S speech unscripted': ['Spoken', 'lectures'],
 'S sportslive': ['Spoken', 'talk'],
 'S tutorial': ['Spoken', 'talk'],
 'S unclassified': ['Spoken', 'spoken others'],
 'W ac humanities arts': ['Written', 'academic', 'humanities arts'],
 'W ac medicine': ['Written', 'academic', 'medicine'],
 'W ac nat science': ['Written', 'academic', 'natural science'],
 'W ac polit law edu': ['Written', 'academic', 'politics, law, education'],
 'W ac soc science': ['Written', 'academic', 'social science'],
 'W ac tech engin': ['Written', 'academic', 'technological engineering'],
 'W admin': ['Written', 'non-academic'],
 'W advert': ['Written', 'non-academic'],
 'W biography': ['Written', 'non-academic'],
 'W commerce': ['Written', 'non-academic'],
 'W email': ['Written', 'letter'],
 'W essay school': ['Written', 'academic', 'students'],
 'W essay univ': ['Written', 'academic', 'students'],
 'W fict drama': ['Written', 'fiction'],
 'W fict poetry': ['Written', 'fiction'],
 'W fict prose': ['Written', 'fiction'],
 'W hansard': ['Written', 'written others'],
 'W institut doc': ['Written', 'non-academic'],
 'W instructional': ['Written', 'non-academic'],
 'W letters personal': ['Written', 'letter'],
 'W letters prof': ['Written', 'letter'],
 'W misc': ['Written', 'written others'],
 'W news script': ['Written', 'newspaper', 'others'],
 'W newsp brdsht nat arts': ['Written', 'newspaper', 'arts '],
 'W newsp brdsht nat commerce': ['Written', 'newspaper', 'commerce'],
 'W newsp brdsht nat editorial': ['Written', 'newspaper', 'editorial'],
 'W newsp brdsht nat misc': ['Written', 'newspaper', 'others'],
 'W newsp brdsht nat report': ['Written', 'newspaper', 'report'],
 'W newsp brdsht nat science': ['Written', 'newspaper', 'science'],
 'W newsp brdsht nat social': ['Written', 'newspaper', 'social'],
 'W newsp brdsht nat sports': ['Written', 'newspaper', 'sports'],
 'W newsp other arts': ['Written', 'newspaper', 'arts '],
 'W newsp other commerce': ['Written', 'newspaper', 'commerce'],
 'W newsp other report': ['Written', 'newspaper', 'report'],
 'W newsp other science': ['Written', 'newspaper', 'science'],
 'W newsp other social': ['Written', 'newspaper', 'social'],
 'W newsp other sports': ['Written', 'newspaper', 'sports'],
 'W newsp tabloid': ['Written', 'newspaper', 'others'],
 'W nonAc humanities arts': ['Written', 'popular science', 'humanities arts'],
 'W nonAc medicine': ['Written', 'popular science', 'medicine'],
 'W nonAc nat science': ['Written', 'popular science', 'natural science'],
 'W nonAc polit law edu': ['Written', 'popular science', 'politics, law, education'],
 'W nonAc soc science': ['Written', 'popular science', 'social science'],
 'W nonAc tech engin': ['Written', 'popular science', 'technological engineering'],
 'W pop lore': ['Written', 'lore & religion'],
 'W religion': ['Written', 'lore & religion']}

smp_bnc_classcode = {'S lectures': ['Spoken', 'lectures'], 'S talk': ['Spoken', 'talk'], 'W academic technological engineering': ['Written', 'academic', 'technological engineering'], 'W newspaper commerce': ['Written', 'newspaper', 'commerce'], 'W academic politics, law, education': ['Written', 'academic', 'politics, law, education'], 'W academic social science': ['Written', 'academic', 'social science'], 'W academic humanities arts': ['Written', 'academic', 'humanities arts'], 'W newspaper arts ': ['Written', 'newspaper', 'arts '], 'W letter': ['Written', 'letter'], 'W fiction': ['Written', 'fiction'], 'W newspaper social': ['Written', 'newspaper', 'social'], 'W non-academic': ['Written', 'non-academic'], 'W lore & religion': ['Written', 'lore & religion'], 'W newspaper editorial': ['Written', 'newspaper', 'editorial'], 'W academic medicine': ['Written', 'academic', 'medicine'], 'W academic students': ['Written', 'academic', 'students'], 'W newspaper sports': ['Written', 'newspaper', 'sports'], 'W academic natural science': ['Written', 'academic', 'natural science'], 'W popular science politics, law, education': ['Written', 'popular science', 'politics, law, education'], 'S spoken others': ['Spoken', 'spoken others'], 'W written others': ['Written', 'written others'], 'W popular science humanities arts': ['Written', 'popular science', 'humanities arts'], 'W newspaper science': ['Written', 'newspaper', 'science'], 'W popular science social science': ['Written', 'popular science', 'social science'], 'W popular science technological engineering': ['Written', 'popular science', 'technological engineering'], 'W popular science natural science': ['Written', 'popular science', 'natural science'], 'W newspaper others': ['Written', 'newspaper', 'others'], 'W newspaper report': ['Written', 'newspaper', 'report'], 'W popular science medicine': ['Written', 'popular science', 'medicine']}
