bnc_classcode = {'S brdcast discussn': ['S', 'talk'],
 'S brdcast documentary': ['S', 'talk'],
 'S brdcast news': ['S', 'talk'],
 'S classroom': ['S', 'talk'],
 'S consult': ['S', 'talk'],
 'S conv': ['S', 'talk'],
 'S courtroom': ['S', 'talk'],
 'S demonstratn': ['S', 'talk'],
 'S interview': ['S', 'talk'],
 'S interview oral history': ['S', 'talk'],
 'S lect commerce': ['S', 'lectures'],
 'S lect humanities arts': ['S', 'lectures'],
 'S lect nat science': ['S', 'lectures'],
 'S lect polit law edu': ['S', 'lectures'],
 'S lect soc science': ['S', 'lectures'],
 'S meeting': ['S', 'talk'],
 'S parliament': ['S', 'talk'],
 'S pub debate': ['S', 'talk'],
 'S sermon': ['S', 'lectures'],
 'S speech scripted': ['S', 'lectures'],
 'S speech unscripted': ['S', 'lectures'],
 'S sportslive': ['S', 'talk'],
 'S tutorial': ['S', 'talk'],
 'S unclassified': ['S', 'spoken others'],
 'W ac humanities arts': ['W', 'academic', 'humanities arts'],
 'W ac medicine': ['W', 'academic', 'medicine'],
 'W ac nat science': ['W', 'academic', 'natural science'],
 'W ac polit law edu': ['W', 'academic', 'politics, law, education'],
 'W ac soc science': ['W', 'academic', 'social science'],
 'W ac tech engin': ['W', 'academic', 'technological engineering'],
 'W admin': ['W', 'non-academic'],
 'W advert': ['W', 'non-academic'],
 'W biography': ['W', 'non-academic'],
 'W commerce': ['W', 'non-academic'],
 'W email': ['W', 'letter'],
 'W essay school': ['W', 'academic', 'students'],
 'W essay univ': ['W', 'academic', 'students'],
 'W fict drama': ['W', 'fiction'],
 'W fict poetry': ['W', 'fiction'],
 'W fict prose': ['W', 'fiction'],
 'W hansard': ['W', 'written others'],
 'W institut doc': ['W', 'non-academic'],
 'W instructional': ['W', 'non-academic'],
 'W letters personal': ['W', 'letter'],
 'W letters prof': ['W', 'letter'],
 'W misc': ['W', 'written others'],
 'W news script': ['W', 'newspaper', 'others'],
 'W newsp brdsht nat arts': ['W', 'newspaper', 'arts '],
 'W newsp brdsht nat commerce': ['W', 'newspaper', 'commerce'],
 'W newsp brdsht nat editorial': ['W', 'newspaper', 'editorial'],
 'W newsp brdsht nat misc': ['W', 'newspaper', 'others'],
 'W newsp brdsht nat report': ['W', 'newspaper', 'report'],
 'W newsp brdsht nat science': ['W', 'newspaper', 'science'],
 'W newsp brdsht nat social': ['W', 'newspaper', 'social'],
 'W newsp brdsht nat sports': ['W', 'newspaper', 'sports'],
 'W newsp other arts': ['W', 'newspaper', 'arts '],
 'W newsp other commerce': ['W', 'newspaper', 'commerce'],
 'W newsp other report': ['W', 'newspaper', 'report'],
 'W newsp other science': ['W', 'newspaper', 'science'],
 'W newsp other social': ['W', 'newspaper', 'social'],
 'W newsp other sports': ['W', 'newspaper', 'sports'],
 'W newsp tabloid': ['W', 'newspaper', 'others'],
 'W nonAc humanities arts': ['W', 'popular science', 'humanities arts'],
 'W nonAc medicine': ['W', 'popular science', 'medicine'],
 'W nonAc nat science': ['W', 'popular science', 'natural science'],
 'W nonAc polit law edu': ['W', 'popular science', 'politics, law, education'],
 'W nonAc soc science': ['W', 'popular science', 'social science'],
 'W nonAc tech engin': ['W', 'popular science', 'technological engineering'],
 'W pop lore': ['W', 'lore & religion'],
 'W religion': ['W', 'lore & religion']}

smp_bnc_classcode = {'S lectures': ['S', 'lectures'], 'S talk': ['S', 'talk'], 'W academic technological engineering': ['W', 'academic', 'technological engineering'], 'W newspaper commerce': ['W', 'newspaper', 'commerce'], 'W academic politics, law, education': ['W', 'academic', 'politics, law, education'], 'W academic social science': ['W', 'academic', 'social science'], 'W academic humanities arts': ['W', 'academic', 'humanities arts'], 'W newspaper arts ': ['W', 'newspaper', 'arts '], 'W letter': ['W', 'letter'], 'W fiction': ['W', 'fiction'], 'W newspaper social': ['W', 'newspaper', 'social'], 'W non-academic': ['W', 'non-academic'], 'W lore & religion': ['W', 'lore & religion'], 'W newspaper editorial': ['W', 'newspaper', 'editorial'], 'W academic medicine': ['W', 'academic', 'medicine'], 'W academic students': ['W', 'academic', 'students'], 'W newspaper sports': ['W', 'newspaper', 'sports'], 'W academic natural science': ['W', 'academic', 'natural science'], 'W popular science politics, law, education': ['W', 'popular science', 'politics, law, education'], 'S spoken others': ['S', 'spoken others'], 'W written others': ['W', 'written others'], 'W popular science humanities arts': ['W', 'popular science', 'humanities arts'], 'W newspaper science': ['W', 'newspaper', 'science'], 'W popular science social science': ['W', 'popular science', 'social science'], 'W popular science technological engineering': ['W', 'popular science', 'technological engineering'], 'W popular science natural science': ['W', 'popular science', 'natural science'], 'W newspaper others': ['W', 'newspaper', 'others'], 'W newspaper report': ['W', 'newspaper', 'report'], 'W popular science medicine': ['W', 'popular science', 'medicine']}
